### ISSUE TITLE
Install has a problem

### ISSUE THREAD

**Issue by 16sgit** [trampgeek/jobe#23]
An error occurred when I executed my order ：
          # sudo ./install
    File "./install", line 48
    names = {ps_line.split(' ')[0] for ps_line in ps_lines}
                                     ^
SyntaxError: invalid syntax

**Comment by trampgeek** [comment]
Can you check what version of Python is installed on your machine please? The Jobe installer needs at least Python 2.7.

**Comment by 16sgit** [comment]
I see. Thank you

**Comment by 16sgit** [comment]
After I installed Python 2.7.10, I ran into a new problem ：
          Configuring for 10 simultaneous job runs
         Exception during install: Couldn't determine web-server user id. Is the web server running?
         Install failed
Please tell me how to solve it. Thank you very much

**Comment by trampgeek** [comment]
What flavour of Linux are you running?
Assuming the web server is running, what user_id does it have?
Line 48 in the install script

    candidates = names.intersection(set(['apache', 'www-data']))

assumes the the web-server user id is either `apache` or `www-data`. Is it something else on your system, perhaps? I vaguely recall it was `httpd` on one system. If so, you could change line 48 to

    candidates = names.intersection(set(['apache', 'www-data', 'httpd']))

**Comment by trampgeek** [comment]
Actually I think the fix for CentOS (is that what you're running?) is a couple of lines earlier, around line 46. Change the first line of `get_webserver`  to

    ps_cmd = "ps aux | egrep /usr/sbin/(apache2|httpd)"

I've pushed a new version of the install script today with that patch in it.
I've also pushed an updated version of the documentation. I've added a new paragraph to the Installation instructions, which might be relevant if anything else goes wrong:

"Installation on Ubuntu 16.04 systems should be straightforward but installation on other flavours of Linux or on systems with non-standard configurations may require Linux administrator skills. A possible alternative approach if things go wrong is to try the experimental JobeInABox Docker image, which should be runnable with a single terminal command on any Linux system that has docker installed. Thanks to David Bowes (UHerts) for most of the work on this. Please be aware that it is still experimental and hasn't been used in production by the author. Feedback is welcomed."

**Comment by 16sgit** [comment]
Thank you for your reply. I need to have a try

**Comment by 16sgit** [comment]
Hello, I installed the Ubuntu 16.04 system using VMware. BuT Now I have a new problem:
       root@admin:/var/www/html/jobe# sudo ./install
      Configuring for 10 simultaneous job runs
      /bin/sh: 1: Syntax error: "(" unexpected
      Exception during install: Command 'ps aux | egrep /usr/sbin/(apache2|httpd)' returned non-zero exit 
     status 2
     Install failed
Think  you

**Comment by trampgeek** [comment]
Yowch. My last push (8 days ago) introduced that bug. Sorry. Should be 
fixed now.

**Comment by 16sgit** [comment]
Think you How to solve the problem :
    root@admin:/var/www/html/jobe# sudo ./install
Configuring for 10 simultaneous job runs
Exception during install: Command 'ps aux | egrep '/usr/sbin/(apache2|httpd)'' returned non-zero exit status 1
Install failed

**Comment by trampgeek** [comment]
You don't appear to have pulled the fix I pushed to github, namely to 
change that line to

ps_cmd ="ps aux | egrep '/usr/sbin/(apache2|httpd)'"

Richard

**Comment by 16sgit** [comment]
Thank you for your reply, but I still don't know how to do it after your reply
  In my code that line is  
           ps_cmd ="ps aux | egrep '/usr/sbin/(apache2|httpd)'"
  What do i need to do

**Comment by trampgeek** [comment]
Ah, ok. Your previous posting had just a double quote at the end of that line and I thought that was the problem.

It looks like Apache isn't running. Did you run the commands given in the Jobe readme file? Specifically:

        apt-get install apache2 php libapache2-mod-php php-mcrypt mysql-server\
          php-mysql php-cli octave nodejs\
          git python3 build-essential openjdk-9-jre openjdk-9-jdk python3-pip\
          fp-compiler pylint3 acl
        pylint --reports=no --generate-rcfile > /etc/pylintrc

They need to be run before attempting the Jobe install.

If you did run those commands and Apache isn't running, you'll need to find out why. You could start by rebooting, then trying commands like `sudo service apache2 restart`. But it's strange, because installing on Ubuntu 16.04 is normally straightforward.

**Comment by trampgeek** [comment]
Closing as no recent communications.
